import "../styles/globals.css";
import Head from "next/head";
import { Provider } from "react-redux";
import store from "../redux/store";
import GlobalStyle from "../styles/globalStyle";
import "bootstrap/dist/css/bootstrap.min.css";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Valex - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/valex.png" />
        <script src="//code-eu1.jivosite.com/widget/FcyQqOXV14" async></script>
      </Head>
      <Provider store={store}>
        <GlobalStyle />
        <Component {...pageProps} />
      </Provider>
    </>
  );
}

export default MyApp;
